import {
  Apple,
  Backpack,
  Bike,
  Camera,
  Car,
  Cherry,
  Cloud,
  Coffee,
  Cookie,
  Flower,
  Gift,
  Glasses,
  Heart,
  IceCream,
  Leaf,
  Music,
  Pizza,
  Shirt,
  Snowflake,
  Star,
  Sun,
  TreePine,
  Umbrella,
  Watch,
  type LucideIcon,
} from 'lucide-react'

/** iconKey (see lib/game/story-memory-data.ts#MemoryObjectDef) -> lucide component. Kept in components/ (not lib/) since it holds React component references. */
export const OBJECT_MEMORY_ICON_MAP: Record<string, LucideIcon> = {
  umbrella: Umbrella,
  shirt: Shirt,
  glasses: Glasses,
  watch: Watch,
  backpack: Backpack,
  gift: Gift,
  apple: Apple,
  cherry: Cherry,
  'ice-cream': IceCream,
  coffee: Coffee,
  pizza: Pizza,
  cookie: Cookie,
  leaf: Leaf,
  flower: Flower,
  'tree-pine': TreePine,
  sun: Sun,
  cloud: Cloud,
  snowflake: Snowflake,
  car: Car,
  bike: Bike,
  star: Star,
  heart: Heart,
  music: Music,
  camera: Camera,
}
